javac -d . java_miniproject/Styles.java
javac -d . java_miniproject/PrivateDB.java
javac -d . java_miniproject/UserDBUtilities.java
javac -d . java_miniproject/ErrorDialog.java
javac -d . java_miniproject/Encryption.java
javac -d . java_miniproject/ActionCnfm.java
javac -d . java_miniproject/SignUp.java
javac -d . java_miniproject/CompleteView.java
javac -d . java_miniproject/ListItem.java
javac -d . java_miniproject/NewPassword.java
javac -d . java_miniproject/ChangeProperty.java
javac -d . java_miniproject/Home.java
javac -d . java_miniproject/LogIn.java
java -cp ".;lib/sqlite-jdbc-3.32.3.2.jar" java_miniproject.LogIn